name: CI Process

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run Tests with JaCoCo
        run: mvn test jacoco:report

      - name: Verify 100% Branch Coverage
        run: mvn jacoco:check

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: target/site/jacoco/
